### ISSUE TITLE
抖音视频解析

### ISSUE THREAD

**Issue by mayishidai** [zbfzn/douyin-quick#3]
新接口解析出来的抖音，貌似最多只有30秒，不知作者有没有察觉到这个变化呢

**Comment by zbfzn** [comment]
能否给一下出现问题的视频链接

**Comment by mayishidai** [comment]
比如这种，
http://v6-dy.ixigua.com/72688f7498a22b7e898a2717e93a37f8/5cfe65ce/video/m/220bc2cd25f5c6a46ceb94d5a1afc75638a11626618700001a1e52e06889/?rc=ajN4ZWc4dDR5bTMzOmkzM0ApQHRAbzo6OTw1NjozNDs3NDM5PDNAKXUpQGczdSlAZjN2KUBmaHV5cTFmc2hoZGY7NEAtaXFfX2QybXBfLS1eLS9zczVvI28jNjIwLTAtLi0tLS4vLi0uL2k6Yi5wIzphLXEjOmAwbyNwYmZyaF4ranQ6Iy8uXg%3D%3D
他不是熟悉的短链接，而且不能下载，直接复制出来的链接，用浏览器打开都可以下载，但是仅仅只有30s
 
---原始邮件---
发件人: "zbfzn"<notifications@github.com>
发送时间: 2019年6月10日 21:09:21
收件人: "zbfzn/douyin-quick"<douyin-quick@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"13551527194"<1620829248@qq.com>;
主题: Re: [zbfzn/douyin-quick] 抖音视频解析 (#3)



能否给一下出现问题的视频链接

**Comment by mayishidai** [comment]
通过二维码进入观看，和最开始看到的不一样
最开始看到的直接是一个很长的视频，不能下载
通过刚才二维码进入，看到的是，标题下方有一个完整视频链接，解析到的是外面的30s预览版本，里面的详细的就没法进行解析了


 
---原始邮件---
发件人: "zbfzn"<notifications@github.com>
发送时间: 2019年6月10日 21:09:21
收件人: "zbfzn/douyin-quick"<douyin-quick@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"13551527194"<1620829248@qq.com>;
主题: Re: [zbfzn/douyin-quick] 抖音视频解析 (#3)



能否给一下出现问题的视频链接

**Comment by zbfzn** [comment]
我刚刚上传了编译好的完整视频下载版本的APK文件，你下载安装就可以下载完整视频了

**Comment by mayishidai** [comment]
👍点赞


 
---原始邮件---
发件人: "zbfzn"<notifications@github.com>
发送时间: 2019年6月10日 21:28:43
收件人: "zbfzn/douyin-quick"<douyin-quick@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"13551527194"<1620829248@qq.com>;
主题: Re: [zbfzn/douyin-quick] 抖音视频解析 (#3)



我刚刚上传了编译好的完整视频下载版本的APK文件，你下载安装就可以下载完整视频了

**Comment by mayishidai** [comment]
![JAUK8W$}(M~~7W3P5JETK8U (1)](https://user-images.githubusercontent.com/20534392/59199586-ded91700-8bc8-11e9-9523-28b91ed4df17.jpg)
![S@O62R)(9JZ@V$ A5`J{U(M (1)](https://user-images.githubusercontent.com/20534392/59199587-df71ad80-8bc8-11e9-8e40-fb4fa701eda2.jpg)
![UIE`Y %G_09H6ZUS( WSGKC](https://user-images.githubusercontent.com/20534392/59199588-df71ad80-8bc8-11e9-9583-6df71078d149.jpg)

始终无法解析最里面的完整视频，它没有分享链接，它是二维码的
通过作者的主页进去看，没有下方的完整视频，可以全看完，但是解析到的，依然只有30S

**Comment by mayishidai** [comment]
![S@O62R)(9JZ@V$ A5`J{U(M (1)](https://user-images.githubusercontent.com/20534392/59199726-3d9e9080-8bc9-11e9-9293-223f7b06d6ff.jpg)
